version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - docsify
    #    condition: service_healthy  # docsifyがhealthy状態になるまで待機
    networks:
      - oss_network

  docsify:
    image: sujaykumarh/docsify
    container_name: docsify
    volumes:
      - ./docs:/docs  # ホストの./docsディレクトリをコンテナの/docsディレクトリにマウント
    environment:
      - PORT=3000
    command: ["/usr/local/bin/docsify", "serve", "/docs"]  # docsifyのコマンドを明示的に指定
    #healthcheck:  # healthcheckを追加
     # test: ["CMD", "curl", "-f", "http://localhost:3000"]  # 3000番ポートの確認
     # interval: 10s
     # timeout: 5s
     # retries: 3
     # start_period: 5s  # docsifyが起動するまでの待機期間
    networks:
      - oss_network

networks:
  oss_network:
    external: true
  #  driver: bridge
