version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - docsify

  docsify:
    image: sujaykumarh/docsify
    container_name: docsify
    volumes:
      - ./docs:/docs  # ホストの./docsディレクトリをコンテナの/docsディレクトリにマウント
    environment:
      - PORT=3000
    command: docsify serve /docs

networks:
  default:
    external:
      name: nginx_network
